export const BASIC_TYPE_NUMBER = 'number'
export const BASIC_TYPE_STRING = 'string'
export const BASIC_TYPE_FUN = 'function'
export const BASIC_TYPE_ARRAY = 'array'
export const BASIC_TYPE_OBJECT = 'object'
export const BASIC_TYPE_BOOL = 'boolean'
export const BASIC_TYPE_REACTNODE = 'ReactNode'